version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: logic
      POSTGRES_DB: smart_bas_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=your_db_name
      - DATABASE_USER=your_db_user
      - DATABASE_PASSWORD=your_db_password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

volumes:
  postgres_data:
