# Generated by Django 6.0 on 2026-01-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='test_field',
            field=models.BooleanField(default=False),
        ),
    ]
