# Generated by Django 6.0 on 2026-02-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_productcategory_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('PROCESSING', 'Processing'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=10),
        ),
    ]
